#Los contenedores que forman la app
services:
  # Contenedor 1
  server:
    container_name: app-server
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: npm start

  client:
    container_name: app-client
    build: ./client
    ports:
      - "${CLIENT_PORT}:${NGINX_PORT}"
    # Espera a que el contenedor del server haya iniciado primero
    depends_on:
      - server